name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
      ## Introduction
      Please write your bug report in English. If you are not comfortable with English, we recommend using translation tools like Google Translate, DeepL, ChatGPT, etc.

  - type: markdown
    attributes:
      value: "## Forms"

  - type: checkbox
    id: no_duplicate
    attributes:
      label: "I confirm that this bug report does not already exist in Issues."

  - type: textarea
    id: bug_details
    attributes:
      label: "Bug Description"
      description: "Please provide a detailed description of the bug you encountered. Avoid overly simple inputs unless it is a simple bug."

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide detailed steps to reproduce the bug you encountered."

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshot (optional)"
      description: "You can optionally screenshots can be attached. See "[Attaching files - GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)" for more information about attachable files."

  - type: markdown
    attributes:
      value: "Thank you for your help in improving Better Styles!"
