name: Feature Request
description: Suggest an idea or enhancement for the project.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
      ## Introduction
      Please write your bug report in English. If you are not comfortable with English, we recommend using translation tools like Google Translate, DeepL, ChatGPT, etc.

  - type: markdown
    attributes:
      value: "## Forms"

  - type: checkbox
    id: no_duplicate
    attributes:
      label: "I have verified that the same request does not exist in Issues."

  - type: textarea
    id: feature_needed
    attributes:
      label: "What feature is needed?"
      description: "Please describe the feature you would like to see added to the project."

  - type: textarea
    id: feature_use
    attributes:
      label: "Why is the feature needed and how it will be used?"
      description: "Please describe why the feature is needed and how it will be used."

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshot (optional)"
      description: "You can optionally screenshots can be attached. See "[Attaching files - GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)" for more information about attachable files."

  - type: markdown
    attributes:
      value: "Thank you for your help in improving Better Styles!"
